sequence_file: None
protocol: sequence_to_value
model_choice: FNN
optimizer_choice: adam
loss_choice: mean_squared_error
num_epochs: 20
use_class_weights: False
learning_rate: 1e-3
batch_size: 256
embedder_name: prottrans_t5_uniref50
ignore_file_inconsistencies: True
save_split_ids: True
cross_validation_config:
  method: hold_out
