sequence_file: None
labels_file: None
protocol: sequence_to_class
model_choice: FNN
optimizer_choice: adam
loss_choice: cross_entropy_loss
num_epochs: 20
use_class_weights: False
learning_rate: 1e-3
batch_size: 128
embedder_name: prottrans_t5_uniref50
embeddings_file: None